### ISSUE TITLE
Polymer transformer issue

### ISSUE THREAD

**Issue by vsheyanov** [dart-lang/polymer-dart#62] opened 2015-04-24 14:26 UTC
Hi guys.
Sample app: https://gist.github.com/vsheyanov/5ae29f9853b532f49e5b

In Chrome I see this (which is what I expect actually)
![right](https://cloud.githubusercontent.com/assets/1764195/7320699/e21e1da6-eaa6-11e4-9039-3af8019b3d07.png)
In Firefox (which I think is wrong):
![wrong](https://cloud.githubusercontent.com/assets/1764195/7320716/fe34bfae-eaa6-11e4-8fec-84a079e0628a.png)

I'm not sure if this is an issue or my expectations are wrong.

**Comment by jakemac53** [comment] 2015-04-24 14:52
This is a pitfall of the way the shadow dom css polyfill works today, styles from parent elements will leak into their children. See [this page](https://www.polymer-project.org/0.5/docs/polymer/styling.html#strictstyling) for how you can enable this behavior, but its pretty painful :(. I haven't tried doing it in dart, but you should be able to  use js interop to tweak the polyfill settings as described there.

Closing for now, as this is working as intended unfortunately.

**Closed by jakemac53** 2015-04-24 14:52 UTC

**Comment by vsheyanov** [comment] 2015-05-13 16:21
I remembered that when I tried AngularDart this stuff worked out of the box. I checked and looks like Angular folks did a great job on shimming stuff as they add empty attributes for every tag inside custom element to support strictly styling. My example works as expected in Firefox when written using Angular.
I hope PolymerDart would have something similar someday :)
