### ISSUE TITLE
fire() seems not to work

### ISSUE THREAD

**Issue by zoechi** [dart-lang/polymer-dart#643] opened 2015-11-15 12:27 UTC
https://github.com/bwu-dart/polymer_elements_demos/blob/6f21c3acdea85b5e7c98494951e23475bc15dd22/web/prism_element/prism_demo.dart#L38

The `<prism-highlighter>` (in the local DOM) listens for `syntax-highlight` on the parent (`<prism-demo>`) but doesn't receive the event.
When I add an event handler in `<prism-demo>` itself, it also doesn't receive the event.

Should this work this way?

**Comment by jakemac53** [comment] 2015-11-16 15:03
There is a basic test here which is passing https://github.com/dart-lang/polymer_interop/blob/1.0.0-rc.5/test/polymer_base_test.dart#L152. Seems like an issue with the element?

**Comment by zoechi** [comment] 2015-11-16 16:25
It's often helpful to talk to someone about the problem ;-)
I added `async(...)` and now it's working. 

This is the 2nd time I run into this issue. 
It seems to work in JS but not in Dart when code is run from a property observer.
There seems to be some timing difference.

**Comment by zoechi** [comment] 2015-11-16 16:25
And thanks for looking into it :+1:

**Comment by jakemac53** [comment] 2015-11-16 16:27
Definitely weird, I will look into this a bit.

**Comment by jakemac53** [comment] 2015-11-16 16:39
Hmm I actually don't see the error? Tried regular server in dartium as well as pub serve in dartium/chrome.

**Comment by zoechi** [comment] 2015-11-16 17:31
Now I can't anymore either  :disappointed: or better :smile: 
Maybe it worked all the time, but I have no idea why the breakpoint didn't hit previously, but then with `async()` it did.

I now run into another issue. Maybe this tricked me into thinking that the event wasn't processed.
When I call 
```dart
var result = fire('syntax-highlight', detail: {'code': code, 'lang': lang});
```
```dart
result.detail['code']
```
should return the highlighted result but I get the result only with this code
```dart
(result as CustomEventWrapper).original.detail['code'];
```

**Comment by zoechi** [comment] 2015-11-16 17:33
Actually I still need `async()`

**Comment by zoechi** [comment] 2015-11-16 17:42
Could this depend on the performance of the used machine? 
Mine is a bit outdated. It was a powerful notebook once, but is now several years old.

**Comment by jakemac53** [comment] 2015-11-17 14:52
It certainly could, although I would hope its not haha. I think its more likely different dartium versions or something along those lines.

**Comment by zoechi** [comment] 2015-11-17 15:49
Ok, I'll monitor it and try to find a way to make it reproducable.
What do you think about the `detail` not being updated on the return value of `fire(...)`?

**Comment by jakemac53** [comment] 2015-11-18 22:05
> What do you think about the detail not being updated on the return value of fire(...)?

Not sure on that one, definitely should work. I can investigate it shortly.

**Comment by jakemac53** [comment] 2015-11-18 22:11
hmm I just tried 

```
var event = fire('my-event', detail: {'foo': 'bar'});
print(event.detail['foo']);
```

and that printed `bar` as expected?

**Comment by zoechi** [comment] 2015-11-18 22:13
In the demo where I run into this, an event handler updates the `detail` content, and this updated data is not available (only in `event.original.detail`).
The value I passed to `fire()` was there, but that's not what's needed.

**Comment by jakemac53** [comment] 2015-11-18 22:23
oh... ya that is just not going to work today :(

**Comment by jakemac53** [comment] 2015-11-18 22:31
been debating this for a while.... but we could just implement a wrapper around JsObject instead of converting them to a Map. That is probably the safer choice but definitely a breaking change. Could do the same for List/JsArray as well.

**Comment by jakemac53** [comment] 2016-03-14 14:03
closing as a dupe of https://github.com/dart-lang/polymer-dart/issues/586

**Closed by jakemac53** 2016-03-14 14:03 UTC
