### ISSUE TITLE
v16.0+1 Second level repeat binding is broken.

### ISSUE THREAD

**Issue by kzhdev** [dart-lang/polymer-dart#36] opened 2015-03-16 23:44 UTC
Please see following link for details:

https://code.google.com/p/dart/issues/detail?id=22863&sort=-opened&colspec=ID%20Type%20Status%20Priority%20Area%20Milestone%20Owner%20Summary%20Modified%20Opened

**Comment by jakemac53** [comment] 2015-03-17 19:51
Looks like the same issue as the one discussed at the end here https://github.com/dart-lang/polymer-dart/issues/33. I have a fix in flight [here](https://codereview.chromium.org/1018643002/). With that I was able to just increase the polymer upper bound, run pub upgrade, and everything works fine.

**Comment by jakemac53** [comment] 2015-03-17 22:58
should be fixed now if you do a pub upgrade (make sure you get 0.5.1+7 of the `initialize`  package)

**Comment by kzhdev** [comment] 2015-03-18 03:08
This is not fixed in 0.16.0+1.

**Comment by kzhdev** [comment] 2015-03-18 04:28
@jakemac53 

After upgrading to v0.16.0+1 (0.5.1+7 for initialize), the issue is fixed for using <link ref="impor" ...> in .html template. However, it is still a issue if using @HtmlImport("...html") in .dart file.

**Comment by jakemac53** [comment] 2015-03-18 14:27
I just attached a version to the original dart bug which has been converted over to @HtmlImport for everything and it seems to be working fine. I didn't have a chance to look to much into the version that you did, but I can confirm its not working for me either, there must be some subtle difference there which is escaping me.

**Comment by jakemac53** [comment] 2015-03-18 14:41
Ah found it, looks like this has to do with how you are using exports instead of imports (probably to hide the unused import hints). This should work, although its probably exposing more than you really want to the outside world. If your only goal is to hide the hint then I would recommend a dartdoc comment instead, for instance add something like this to your class will hide the hint for any import containing a ToolButtonGroup class:

/// Using [ToolButtonGroup] in the template.

**Comment by jakemac53** [comment] 2015-03-18 15:03
fix pending here https://codereview.chromium.org/1011743006/, should be in by EOD

**Comment by kzhdev** [comment] 2015-03-18 15:35
@jakemac53  Thanks!

**Comment by jakemac53** [comment] 2015-03-18 16:30
released as 0.16.0+4, thanks for the report!

**Closed by jakemac53** 2015-03-18 16:30 UTC
