### ISSUE TITLE
Binding with double properties (subtle problem)

### ISSUE THREAD

**Issue by dam0vm3nt** [dart-lang/polymer-dart#627] opened 2015-10-23 10:12 UTC
Calling `notifyPath` on a property of type `double` will cause an error in checked mode if the number have 0 fractional part (for example "867.0"). 
This is caused by JS imperfect type handling. The new value will go through the JS proxy that will automatically cast a `double` with non fractional part to an `int` and then dart will complain about trying to assign an `int` to a `double` field.

**Comment by jakemac53** [comment] 2015-10-23 14:41
:(

**Comment by jakemac53** [comment] 2015-10-23 14:51
I guess the only real solution would be to use `num` instead of `double`. This is really a general js interop issue, and doing reflection on the dart field before each assignment (to convert int to double) isn't really worth it.

Maybe adding in a warning for numeric properties other than `int` and `num` is reasonable.

**Comment by sigmundch** [comment] 2015-10-23 15:22
> .. doing reflection on the dart field before each assignment (to convert int to double) isn't really worth it.

Also, this conversion is not possible in dart2js: dart2js is restricted by how numbers are represented in JS. It's one of those corner cases where the VM and dart2js differ. For example, this Dart program will print true in dart2js, but false in the vm/dartium:

```dart
main() => print(3.0 is int);
```

`num` is probably the best you can do.

**Comment by jakemac53** [comment] 2015-10-23 15:32
I am going to close this as "working as intended" for now, but opened https://github.com/dart-lang/polymer-dart/issues/628

**Closed by jakemac53** 2015-10-23 15:32 UTC

**Comment by dam0vm3nt** [comment] 2015-10-23 16:02
The only (don't know how if actually feasible with current `reflectable`) other solution I had in mine is to check the property type before notifying and forcing a `toDouble` in case... but it is actually not worth and to costly. #628  it's just ok for me.
